// Generated by gencpp from file uorg/konum.msg
// DO NOT EDIT!


#ifndef UORG_MESSAGE_KONUM_H
#define UORG_MESSAGE_KONUM_H

#include <ros/service_traits.h>


#include <uorg/konumRequest.h>
#include <uorg/konumResponse.h>


namespace uorg
{

struct konum
{

typedef konumRequest Request;
typedef konumResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct konum
} // namespace uorg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::uorg::konum > {
  static const char* value()
  {
    return "9910b4d62ca4a80349ae5de1dbbe4d8d";
  }

  static const char* value(const ::uorg::konum&) { return value(); }
};

template<>
struct DataType< ::uorg::konum > {
  static const char* value()
  {
    return "uorg/konum";
  }

  static const char* value(const ::uorg::konum&) { return value(); }
};


// service_traits::MD5Sum< ::uorg::konumRequest> should match
// service_traits::MD5Sum< ::uorg::konum >
template<>
struct MD5Sum< ::uorg::konumRequest>
{
  static const char* value()
  {
    return MD5Sum< ::uorg::konum >::value();
  }
  static const char* value(const ::uorg::konumRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::uorg::konumRequest> should match
// service_traits::DataType< ::uorg::konum >
template<>
struct DataType< ::uorg::konumRequest>
{
  static const char* value()
  {
    return DataType< ::uorg::konum >::value();
  }
  static const char* value(const ::uorg::konumRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::uorg::konumResponse> should match
// service_traits::MD5Sum< ::uorg::konum >
template<>
struct MD5Sum< ::uorg::konumResponse>
{
  static const char* value()
  {
    return MD5Sum< ::uorg::konum >::value();
  }
  static const char* value(const ::uorg::konumResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::uorg::konumResponse> should match
// service_traits::DataType< ::uorg::konum >
template<>
struct DataType< ::uorg::konumResponse>
{
  static const char* value()
  {
    return DataType< ::uorg::konum >::value();
  }
  static const char* value(const ::uorg::konumResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UORG_MESSAGE_KONUM_H
