// Generated by gencpp from file uorg/konumRequest.msg
// DO NOT EDIT!


#ifndef UORG_MESSAGE_KONUMREQUEST_H
#define UORG_MESSAGE_KONUMREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace uorg
{
template <class ContainerAllocator>
struct konumRequest_
{
  typedef konumRequest_<ContainerAllocator> Type;

  konumRequest_()
    : konum()  {
    }
  konumRequest_(const ContainerAllocator& _alloc)
    : konum(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _konum_type;
  _konum_type konum;





  typedef boost::shared_ptr< ::uorg::konumRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uorg::konumRequest_<ContainerAllocator> const> ConstPtr;

}; // struct konumRequest_

typedef ::uorg::konumRequest_<std::allocator<void> > konumRequest;

typedef boost::shared_ptr< ::uorg::konumRequest > konumRequestPtr;
typedef boost::shared_ptr< ::uorg::konumRequest const> konumRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uorg::konumRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uorg::konumRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uorg::konumRequest_<ContainerAllocator1> & lhs, const ::uorg::konumRequest_<ContainerAllocator2> & rhs)
{
  return lhs.konum == rhs.konum;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uorg::konumRequest_<ContainerAllocator1> & lhs, const ::uorg::konumRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uorg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::uorg::konumRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uorg::konumRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uorg::konumRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uorg::konumRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uorg::konumRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uorg::konumRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uorg::konumRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9910b4d62ca4a80349ae5de1dbbe4d8d";
  }

  static const char* value(const ::uorg::konumRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9910b4d62ca4a803ULL;
  static const uint64_t static_value2 = 0x49ae5de1dbbe4d8dULL;
};

template<class ContainerAllocator>
struct DataType< ::uorg::konumRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uorg/konumRequest";
  }

  static const char* value(const ::uorg::konumRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uorg::konumRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/PoseStamped konum\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::uorg::konumRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uorg::konumRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.konum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct konumRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uorg::konumRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uorg::konumRequest_<ContainerAllocator>& v)
  {
    s << indent << "konum: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.konum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UORG_MESSAGE_KONUMREQUEST_H
