// Generated by gencpp from file uorg/konumResponse.msg
// DO NOT EDIT!


#ifndef UORG_MESSAGE_KONUMRESPONSE_H
#define UORG_MESSAGE_KONUMRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace uorg
{
template <class ContainerAllocator>
struct konumResponse_
{
  typedef konumResponse_<ContainerAllocator> Type;

  konumResponse_()
    {
    }
  konumResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::uorg::konumResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uorg::konumResponse_<ContainerAllocator> const> ConstPtr;

}; // struct konumResponse_

typedef ::uorg::konumResponse_<std::allocator<void> > konumResponse;

typedef boost::shared_ptr< ::uorg::konumResponse > konumResponsePtr;
typedef boost::shared_ptr< ::uorg::konumResponse const> konumResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uorg::konumResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uorg::konumResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace uorg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::uorg::konumResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uorg::konumResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uorg::konumResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uorg::konumResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uorg::konumResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uorg::konumResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uorg::konumResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::uorg::konumResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::uorg::konumResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uorg/konumResponse";
  }

  static const char* value(const ::uorg::konumResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uorg::konumResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::uorg::konumResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uorg::konumResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct konumResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uorg::konumResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::uorg::konumResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // UORG_MESSAGE_KONUMRESPONSE_H
